### ISSUE TITLE
`bin` -> `lib`

### ISSUE THREAD

**Issue by rbozan** [WilliamVenner/prefer-dynamic#1]
I'm not sure if I need to use this crate but you've specified `bin` on this line:
https://github.com/WilliamVenner/prefer-dynamic/blob/master/build.rs#L37

but the `libstd` is under the `lib` directory (in Linux NixOS), not `bin`. For example:

```
/home/rbozan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libstd-977ece543e1e3d2f.so
```

**Comment by WilliamVenner** [comment]
That's an interesting difference between Windows and Linux. Windows also has a very complex lib/ structure.

**Comment by rbozan** [comment]
Another difference is that on this line:

https://github.com/WilliamVenner/prefer-dynamic/blob/master/build.rs#L66

it states it starts with "std-" but in Linux it's `libstd` (as you can see in the full path above)

**Comment by WilliamVenner** [comment]
Thank you! Fixed.
